# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "bibichan's Master blog"
weight = 1

[zh-tw]
languageName = "Chinese-Traditional"
languagedirection = "ltr"
title = "bibichan 的大師部落格"
weight = 1
