# Rename this file to languages.toml to enable multilingual support
[zh-tw]
  #contentDir = "content"
  languageName = "Chinese Traditonal"
  weight = 1
  title = "bibichan 的大師部落格"
  languageDirection = "ltr"
  languageCode = "zh-TW"
[en]
  contentDir = "content/en"
  languageName = "English"
  weight = 1
  languageDirection = "ltr"
  languageCode = "en-US"
